### ISSUE TITLE
Update Tab: No error displayed if the question does not exist

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#12]
It would be good to have a _"Question does not exist"_ pop-up error if the user selects something that is not in the DB. The API should be throwing a 404 error:

<img width="1672" alt="Screenshot 2020-05-12 at 10 30 47" src="https://user-images.githubusercontent.com/22790804/81668630-dd4d4a00-943c-11ea-8a29-eb8151c8b043.png">

<img width="997" alt="Screenshot 2020-05-12 at 10 39 09" src="https://user-images.githubusercontent.com/22790804/81668644-e0483a80-943c-11ea-810d-60594f2c391f.png">

**Comment by dookah** [comment]
No CORS headers and being passed back with error responses so I can't actually access any status codes. I could implement a generic error if any error gets returned but I imagien you want specific error warnings.

**Comment by JPedro2** [comment]
Updated CORS on Flask to use CORS middleware instead of the decorator: [commit 6f7ee5b](https://github.com/JPedro2/WxT-QA-BOT/commit/6f7ee5bc52a604ed6bd40c17bb79f190e5b99113). Will merge after you tested that works with the Testing ENV

**UPDATE:** Done in PR #21

**Comment by JPedro2** [comment]
This is back on, bringing this issue back so you guys can have a look at the previous commits to bring back the code 😄

**Comment by dookah** [comment]
Woohoo!
