### ISSUE TITLE
Submit&Update: Markdown Cheat sheet typo and reformatting

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#13]
The current cheat sheet has errors like: 
1. `*Bullet Point 1 ` instead of `* Bullet Point 1` (whitespace missing)
2. `# # 2` instead of `##2` (whitespace in between ##)
3. Typo on `Horizontal` line: `Horizonal ` 
4. Need to restructure to show most common ones on top, proposed restructure below.
5. Change name from `Live Preview` to `Markdown Preview`
6. On **Submit Tab** change the _Markdown Cheat Sheet_ bottom height to match and be in line with the _Answer_ text box. This will make the cheat sheet shorter, which IMO is ok, and it will also bring the Markdown Preview box up, which IMO it gives a better UI/X

```
Style:

**BOLD**
_italic_
> Blockquote
`unformatted text`

Links:

[link text](link)
Example: [Cisco Website](www.cisco.com)

Lists:

1. Item1
2. Item2
3. Item3

* Bullet point1
* Bullet point2

Headings:

# Heading 1
## Heading 2
### Heading 3
--- Horizontal Line
```

**Comment by petmorri** [comment]
Closed in #18
