### ISSUE TITLE
Update Tab: Deleting alternative does not work

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#19]
When trying to update an existing question by deleting an existing `alternative b` and then submitting it, the `alternative b` still persists when querying the question again.

Ideally if a question has 2 alternatives and they are load from the Updates tab, then if one is deleted and submitted, next time I query the question only 1 alternative should be present.

From a backEnd perspective this is already possible because wtv the frontEnd submits via the `/UpdateEntry` API is what gets replaced in the DB, so if there are alternative questions and one needs to be deleted then the _alternatives_ `form-data` should look like:

**Old-alternatives:**
`alternatives = "alternative 1 ; alternative2"`

> _user_ deletes 'alternative2' using the `-` button

**new-alternatives-to-be-submitted:**
`alternatives = "alternative 1"`

**Comment by dookah** [comment]
@JPedro2 
I've been testing the function and it seems to be working correctly, I've attached screenshots of the output of the function which generates the alternative question format. 

Two alternatives:
![image](https://user-images.githubusercontent.com/28197795/82032606-6362ce00-9693-11ea-8b09-1315a1a872a4.png)


One alternative (After removing the second alternative):
![image](https://user-images.githubusercontent.com/28197795/82032667-7a092500-9693-11ea-8c07-8ede50a18a75.png)

This is the format the questions are posted in

**Comment by JPedro2** [comment]
@dookah that looks perfect! Can you just make sure that if you delete it as in picture 2 and then submit it, when you query it back the "Test 2" alternative is gone?

**Comment by JPedro2** [comment]
Fixed by @dookah in [0fb5c98](https://github.com/JPedro2/WxT-QA-BOT/commit/0fb5c984572b8ed309955dc60d3140730f1de711) and [efc84d9](https://github.com/JPedro2/WxT-QA-BOT/commit/efc84d92b4deead630298f0a80968dc6ca6cb3a9)
