### ISSUE TITLE
Update Tab: Delete Question not disabled when question is launched

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#35]
After initially selecting a question all the fields are disabled BUT the `Delete Question` - Picture attached.
<img width="1680" alt="Screenshot 2020-05-21 at 10 53 45" src="https://user-images.githubusercontent.com/22790804/82550929-3876ef00-9b57-11ea-9286-bdf0351278a8.png">

After unlocking and locking back again the `Delete Question` button becomes disabled again

**Comment by petmorri** [comment]
Fixed in #36.
