### ISSUE TITLE
Update Tab: The add/delete alternative question buttons (+/-) are static

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#36]
The ➕& ➖buttons used to and should be dynamic and follow the `alternative questions` text box as they are added

<img width="1680" alt="Screenshot 2020-05-21 at 11 36 35" src="https://user-images.githubusercontent.com/22790804/82551253-c652da00-9b57-11ea-98aa-954269a252d4.png">

**Comment by JPedro2** [comment]
Also, can we pin the `Markdown Cheat Sheet`? 
Before, the top of the `Markdown Cheat Sheet` would be pinned and not move as we add more alternatives (see picture above). Only the bottom would move and follow the bottom of the `Answer` text box

**Comment by petmorri** [comment]
I fixed the +/- buttons issue in #37. Still looking into the most elegant way to pin the markdown cheat sheet box.
