### ISSUE TITLE
Unauthorized error does not catch

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#41]
If the user is not logged in (i.e. there's no token) the Unauthorized error code is not being caught and it shows "Submitted Successfully". Although this is not true and obviously nothing is added/modified in the DB. 

<img width="1680" alt="Screenshot 2020-05-23 at 11 59 17" src="https://user-images.githubusercontent.com/22790804/82827583-3a1e1b00-9ea7-11ea-93a8-08bac497c9a4.png">

Need to make sure that if this happens (either on _Submit_ OR _Update_ tabs) the error tells the user that they need to log in and then re-direct them to the login page.

**Comment by dookah** [comment]
Closing this, it shouldn't happen now due to checking posture if the user trys to unlock the page. 
Will solve the issue of users idling the webpage for more than 24 hours then trying to make changes.
