### ISSUE TITLE
Live Preview doesnt scroll

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#5]
If there is a lot of text in the Answer box or even a regular amount of text with a mix of markdown (as shown in the picture) that overflows the Live preview, you lose the ability too see the Live preview past that point as the Live preview does not scroll.

<img width="1680" alt="Screenshot 2020-05-11 at 00 17 00" src="https://user-images.githubusercontent.com/22790804/81513036-5190cc00-931d-11ea-914f-a1606ad52ee1.png">

**Comment by petmorri** [comment]
Should be able to resolve this by adding `overflow: scroll` to `.markup-Area`.

**Comment by JPedro2** [comment]
Sounds good @petmorri ! The code is all up to date, if you can create a new branch to fix this and then make sure that it's all good and raise a PR.. then we can push to prod 😜

**Comment by dookah** [comment]
Fixed Issue, will merge later with other bug fixes.
