### ISSUE TITLE
File-Loaded Workflow

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#7]
Make it more clear that a file is loaded (I think we spoke in calling it attached). I guess moving the button as mentioned in (#2) is already a good start.
The UX can be improved by **opening the file in a new tab** when clicking the button. Currently when the file opens it's on the same tab and it replaces the Dashboard with the GCP Hosted file

**Comment by dookah** [comment]
Buttom moved to right and link opens in new tab.
