### ISSUE TITLE
Submitting alternative questions

### ISSUE THREAD

**Issue by JPedro2** [JPedro2/WxT-QA-BOT#9]
When submitting a Q&A, if you keep adding empty questions it submits them as alternative questions with empty strings. Then when trying to update them, via the update tab, you get that issue as seen in the picture. This will also cause problems in the DB as it will just input empty strings

<img width="1668" alt="Screenshot 2020-05-11 at 00 37 34" src="https://user-images.githubusercontent.com/22790804/81513367-f3191d00-931f-11ea-9509-002b3f81354d.png">

**Comment by dookah** [comment]
Fixed by checking if the string is empty
